version: '2'
services:
  c-open-cultuur-data:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - .:/opt/ocd
    restart: always
    networks:
      - nginx-load-balancer
networks:
  nginx-load-balancer:
    external:
      name: docker_nginx-load-balancer
